/*
 * NewJFrame.java
 *
 * Created on April 11, 2005, 4:55 PM
 */

package prac;

/**
 *
 * @author  Administrator
 */
import java.io.*;

public class NewJFrame extends javax.swing.JFrame {
    
    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        initFileChooser();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */   
    private void initComponents() {//GEN-BEGIN:initComponents
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ULMAN Monitor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setBorder(new javax.swing.border.EtchedBorder());
        jPanel7.setMinimumSize(new java.awt.Dimension(210, 100));
        jLabel1.setText("Time Synchronization");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel1);

        jPanel12.setLayout(new java.awt.GridLayout(0, 1));

        jButton5.setText("jButton5");
        jPanel12.add(jButton5);

        jButton6.setText("jButton6");
        jPanel12.add(jButton6);

        jButton7.setText("jButton7");
        jPanel12.add(jButton7);

        jPanel7.add(jPanel12);

        jPanel1.add(jPanel7, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel5.setBorder(new javax.swing.border.EtchedBorder());
        jPanel5.setMinimumSize(new java.awt.Dimension(165, 75));
        jPanel5.setPreferredSize(new java.awt.Dimension(165, 75));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(new javax.swing.border.EtchedBorder());
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Protocol Manipulation Results");
        jPanel8.add(jLabel4, java.awt.BorderLayout.NORTH);

        jTextArea1.setEditable(false);
        jTextArea1.setForeground(new java.awt.Color(255, 51, 51));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(8);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setDragEnabled(true);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel8.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.GridLayout(0, 1));

        jPanel11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setText("Protocol Manipulation Options");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.add(jLabel2);

        jButton2.setText("Start Routing Protocols");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel11.add(jButton2);

        jButton3.setText("Stop Routing Protocols");
        jPanel11.add(jButton3);

        jButton4.setText("Remove Routing Protocols");
        jPanel11.add(jButton4);

        jPanel5.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setMinimumSize(new java.awt.Dimension(411, 100));
        jLabel5.setText("Enter path or Click Browse Button");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, 20));

        jButton1.setIcon(new javax.swing.ImageIcon("E:\\Prac\\images\\Open16.gif"));
        jButton1.setText("Open Program");
        jButton1.setToolTipText("Open Program");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, 70));

        jLabel3.setText("Activate Network Analyzer And Other Test Scenarios");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel6, java.awt.BorderLayout.SOUTH);

        jTabbedPane1.addTab("Communication And Control", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(new javax.swing.border.EtchedBorder());
        jButton8.setText("jButton8");
        jPanel9.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 10, 100, -1));

        jPanel2.add(jPanel9, java.awt.BorderLayout.WEST);

        jPanel2.add(jPanel10, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Network Monitoring", jPanel2);

        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.addTab("Logging", jPanel3);

        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.addTab("Statistics And Analysis", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String s = "adil raja ";
        for (int i=0; i<100; i++)
        {
            s+="adil raja ";
            this.jTextArea1.setText(s);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int retVal = jFileChooser1.showOpenDialog(NewJFrame.this);
         if (retVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.lang.String fileName = jFileChooser1.getSelectedFile().getAbsolutePath();
            //This is where a real application would open the file.
            try {
                Process p = Runtime.getRuntime().exec(fileName);
                BufferedReader stdInput = new BufferedReader(new 
                InputStreamReader(p.getInputStream()));
                BufferedReader stdError = new BufferedReader(new 
                InputStreamReader(p.getErrorStream()));

 /*           // read the output from the command
            
            System.out.println("Here is the standard output of the command:\n");
            while ((s = stdInput.readLine()) != null) {
                System.out.println(s);
            }
            // read any errors from the attempted command

            System.out.println("Here is the standard error of the command (if any):\n");
            while ((s = stdError.readLine()) != null) {
                System.out.println(s);
            }
            
            System.exit(0);*/
                 }
        catch (IOException e) {
            System.out.println("exception happened - here's what I know: ");
            e.printStackTrace();
  //          System.exit(-1);
        }
//
  //          log.append("Opening: " + file.getName() + ".\n");
        } 
        else{
            log.append("Open command cancelled by user.\n" );
        }
        log.setCaretPosition(log.getDocument().getLength());
    }//GEN-LAST:event_jButton1ActionPerformed
    private void initFileChooser()
    {
        log = new javax.swing.JTextArea(5,20);
        log.setMargin(new java.awt.Insets(5,5,5,5));
        log.setEditable(false);
        this.jFileChooser1 = new javax.swing.JFileChooser();
        this.jFileChooser1.setCurrentDirectory(new java.io.File("C:/dell"));
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JTextArea log;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
